### ISSUE TITLE
Skip builds if a new commit comes through

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#10]

**Comment by sharunkumar** [comment]
I guess you could add concurrency settings but I've seen that usually cancel the old build, which leaves an 'X' on the github commit history

**Comment by arunsathiya** [comment]
Yeah, I handled that in c5796ba5e7b030d3c46fa048c7557f5f1664c1a6 a while ago.

**Comment by arunsathiya** [comment]
Dupe of https://github.com/arunsathiya/portfolio/issues/15
