### ISSUE TITLE
Cache yarn dependencies

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#28]

**Comment by sharunkumar** [comment]
In which workflow?

**Comment by arunsathiya** [comment]
I'm not too sure what I had in mind back then. I think github has some kind of a mechanism to cache dependencies between build processes instead of having to install them every single time. I don't know, I should probably look more into it sometime this weekend.

**Comment by sharunkumar** [comment]
might have to check yarn docs but most liklely there would be an action for it

**Comment by arunsathiya** [comment]
Fixed in https://github.com/arunsathiya/portfolio/pull/67. I think it works:

https://github.com/arunsathiya/portfolio/actions/runs/10606539747/

![Uploading image.png…]()


<img width="1239" alt="image" src="https://github.com/user-attachments/assets/d11c3d76-7580-4e68-85f7-b0c83ee0cefd">
