### ISSUE TITLE
Explore GitHub deployments, vs just tracking deployment progress on workflow runs

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#30]
- https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions
- https://docs.github.com/en/rest/deployments/deployments?apiVersion=2022-11-28#about-deployments
- https://github.com/marketplace/actions/create-deployment-action

**Comment by sharunkumar** [comment]
Do you have multiple deployments? Preview, Production etc?

**Comment by arunsathiya** [comment]
No, only production. Fastly automatically retires the older deployments as new ones come though:

<img width="1381" alt="image" src="https://github.com/user-attachments/assets/19e7061a-385f-43d1-a30a-9688f61807d2">

That's the most I know about this setup. I need to look more into how that ties into GitHub deployments.

**Comment by arunsathiya** [comment]
[Kinda works now](https://github.com/arunsathiya/portfolio/deployments/production), but I don't understand the concepts yet because it reads `ready to deploy`.

<img width="1178" alt="image" src="https://github.com/user-attachments/assets/7f22add5-462d-4f5e-9718-98313fb16a35">

Need to know more about how Fastly Compute deployments can tie into GitHub's concepts.

**Comment by sharunkumar** [comment]
![image](https://github.com/user-attachments/assets/a28515cc-f66c-4b55-83f8-6df86e852499)

**Comment by arunsathiya** [comment]
That "by @arunsathiya" bothers me a bit. 😄 It says so due to my PAT but would be nicer to say `github-actions[bot]` like how we already do for Notion workflow.
