### ISSUE TITLE
whole project needs to be prettier'd

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#37]
whole project needs to be prettier'd

_Originally posted by @sharunkumar in https://github.com/arunsathiya/portfolio/pull/36#discussion_r1729760035_

**Comment by sharunkumar** [comment]
Actually it would be better if we used https://biomejs.dev/

**Comment by sharunkumar** [comment]
> Actually it would be better if we used https://biomejs.dev/

On close inspection, looks like this one has some astro specific prettier rules. so might be worth keeping prettier for now

**Comment by arunsathiya** [comment]
@sharunkumar is this good to close completely?

**Comment by sharunkumar** [comment]
> @sharunkumar is this good to close completely?

Yeah

**Comment by sharunkumar** [comment]
forgot to link the issue, mb
