### ISSUE TITLE
also need to add one more thing - vscode setting to do formatting on save

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#40]
also need to add one more thing - vscode setting to do formatting on save

_Originally posted by @sharunkumar in https://github.com/arunsathiya/portfolio/issues/39#issuecomment-2308146719_

**Comment by arunsathiya** [comment]
I was actually wondering about this. I’m not too familiar with formatting workflow, so you should guide me on this as well.

**Comment by sharunkumar** [comment]
Config im about to add should just automatically be picked up by vscode
