### ISSUE TITLE
Github settings: set squash merge commit messages to take up the PR body

### ISSUE THREAD

**Issue by sharunkumar** [arunsathiya/portfolio#42]
Currently:

![image](https://github.com/user-attachments/assets/0082f635-1377-496c-b28b-6dadf313d710)

**Comment by sharunkumar** [comment]
@arunsathiya why assign to me? I don't have access to repo settings

**Comment by arunsathiya** [comment]
Configured now:

<img width="798" alt="image" src="https://github.com/user-attachments/assets/c3d0ac5a-bc55-4dc0-9cf3-f7a743cf88b6">
