### ISSUE TITLE
Improve the tag colors JSON structure so that it doesn't change often

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#51]
See here: https://github.com/arunsathiya/portfolio/commit/ec3c47f45d77b772ecb4d8d556ea49ed7ba24bd1

I think it should be alphabetically sorted.

**Comment by sharunkumar** [comment]
Verified: https://github.com/arunsathiya/portfolio/commit/15a02c6e5648d972252be39477f7bd0b33570e76
