### ISSUE TITLE
Github settings: Remove 'Deployments' section

### ISSUE THREAD

**Issue by sharunkumar** [arunsathiya/portfolio#52]
![image](https://github.com/user-attachments/assets/e56e11a9-f40e-411f-be23-a6e62e5adf2e)

**Comment by arunsathiya** [comment]
I have a open issue here to explore if Fastly Compute deployments can be made to appear/show on GitHub deployments, like how Vercel does:

https://github.com/arunsathiya/portfolio/issues/30

**Comment by arunsathiya** [comment]
I'll close this in favor of the other one.
