### ISSUE TITLE
Use a GitHub system-level token instead of a PAT for deployments?

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#55]
That "by @arunsathiya" bothers me a bit. 😄 It says so due to my PAT but would be nicer to say `github-actions[bot]` like how we already do for Notion workflow.

_Originally posted by @arunsathiya in https://github.com/arunsathiya/portfolio/issues/30#issuecomment-2308579037_

**Comment by sharunkumar** [comment]
Need to find a way to give github.token the correct access

**Comment by sharunkumar** [comment]
Looks like its was there in the docs all along :cry: 

https://github.com/chrnorm/deployment-action/tree/v2/?tab=readme-ov-file#required-permissions

I forgot to RTFM

**Comment by sharunkumar** [comment]
@arunsathiya you can deplete the PAT

**Comment by sharunkumar** [comment]
![image](https://github.com/user-attachments/assets/4b84fa80-37ff-49e4-91cc-ce8729129521)

**Comment by arunsathiya** [comment]
What really changed?

**Comment by sharunkumar** [comment]
> What really changed?

https://github.com/arunsathiya/portfolio/commit/5c81d861f43d28976ee1571c0830a56b63cc6fd9

**Comment by arunsathiya** [comment]
Yeah, I see that but I am trying to understand what we missed in the original attempt: https://github.com/arunsathiya/portfolio/commit/00959e5ae76cf67baa5619874c7a67f92d6a94fb.

**Comment by sharunkumar** [comment]
> Yeah, I see that but I am trying to understand what we missed in the original attempt: [00959e5](https://github.com/arunsathiya/portfolio/commit/00959e5ae76cf67baa5619874c7a67f92d6a94fb).

this one is unrelated but `altinukshini/deployment-action@releases/v1` is a fork

**Comment by arunsathiya** [comment]
Okay, but in 00959e5ae76cf67baa5619874c7a67f92d6a94fb, aren't we getting rid of `altinukshini/deployment-action@releases/v1` and using `chrnorm/deployment-action@v2`? At that point, with `${{ github.token }}`, why didn't the deployment work? 🤔

**Comment by sharunkumar** [comment]
Both work the same way, both can use github.token. its just that we didn't give permissions to the workflow earlier: https://github.com/arunsathiya/portfolio/blob/main/.github/workflows/build-and-deploy.yml#L18-L19

**Comment by arunsathiya** [comment]
Aha, I missed that. Thanks!
