### ISSUE TITLE
favicon still shows Wordpress icon on mobile

### ISSUE THREAD

**Issue by abishekvenkat** [arunsathiya/portfolio#7]
![image](https://github.com/arunsathiya/portfolio/assets/86376376/8eb1e46f-ea6e-4b48-bede-5bb04d6e53bf)

**Comment by arunsathiya** [comment]
Thanks for the report! Probably cache from my past site, but just to confirm, @sharunkumar, can you reproduce? 

I am unable to. 🤔

**Comment by sharunkumar** [comment]
@abishekvenkat might have to clear your phone's cache. Current favicon is the astro logo

One possible explanation (just a guess, I don't use iPhone) but you might have bookmarked his blog with that favicon and maybe the browser has that saved too, that's something else you could check out

I don't think there's any way from the server side to invalidate favicon cache

**Comment by arunsathiya** [comment]
>I don't think there's any way from the server side to invalidate favicon cache

I remember this being a thing during my WordPress days. Might be an option too for modern frameworks like Astro, gotta research.

**Comment by sharunkumar** [comment]
Even if there is a way, I would not recommend doing it from the server side, cuz you might end up forcing people to download the favicon each time

**Comment by sharunkumar** [comment]
@arunsathiya while we're on the topic I think it would be a neat feature of there was a way, during build time to pull your gravatar and set it as your favicon

**Comment by arunsathiya** [comment]
Not a fan of Gravatar anymore, especially in the context of favicon because a profile photo in that place would be really blurred. I am happy with Astro's branding at the moment, because that "A" matches my name too. 😅

**Comment by sharunkumar** [comment]
> a profile photo in that place would be really blurred

optimize your profile photo then 😎

**Comment by arunsathiya** [comment]
Seems to be astro favicon at the moment. I want to change to something else. Relevant file:

https://github.com/arunsathiya/portfolio/blob/main/public/favicon.svg?plain=1

**Comment by arunsathiya** [comment]
I am okay with this bandaid solution for now:

https://github.com/arunsathiya/portfolio/commit/37365efda0bc021b19453b9355d34b9e302372b3

Ideally I'd want a proper branding and SVG, but something to think of in the future.
